@echo on

SET SERVER={{SERVER}}
SET DATABASE={{DATABASE}}
SET SCHEMA={{SCHEMA}}
SET TABLE={{TABLE}}
SET DATAFILE={{DATAFILE}}
SET FMTFILE={{FMTFILE}}
SET FIRSTROW={{FIRSTROW}}
SET ENCODING={{ENCODING}}
SET BATCHSIZE={{BATCHSIZE}}
SET PACKETSIZE={{PACKETSIZE}}

bcp %DATABASE%.%SCHEMA%.%TABLE% in "%DATAFILE%" ^
-S %SERVER% ^
-T ^
-f "%FMTFILE%" ^
-F %FIRSTROW% ^
-C %ENCODING% ^
-b %BATCHSIZE% ^
-a %PACKETSIZE%

echo bat end
