@echo on

SET SERVER={{SERVER}}
SET DATABASE={{DATABASE}}
SET SCHEMA={{SCHEMA}}
SET TABLE={{TABLE}}
SET DATAFILE={{DATAFILE}}
SET ENCODING={{ENCODING}}
SET PACKETSIZE={{PACKETSIZE}}
SET DELIMITER={{DELIMITER}}
SET ROWTERMINATOR={{ROWTERMINATOR}}

bcp %DATABASE%.%SCHEMA%.%TABLE% out "%DATAFILE%" ^
-S %SERVER% ^
-T ^
-c ^
-C %ENCODING% ^
-t %DELIMITER% ^
-r %ROWTERMINATOR% ^
-a %PACKETSIZE%

echo bat end
